spring:
  application:
    name: nosso-cartao-propostas
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      minimum-idle: 10
      maximum-pool-size: 20
    plataform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${DB_DATABASE:keycloak}
    username: ${DB_USER:keycloak}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/cartao-proposta}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/cartao-proposta/protocol/openid-connect/certs}

uri_analise_financeira: ${URI_ANALISE:http://localhost:9999/}
uri_cartao: http://localhost:8888/

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

logging.level.io.zup.orange.propostaspring.registroProposta.analiseFinanceira.AnaliseFinanceiraDeClientes: DEBUG

management:
  endpoints:
    web:
      cors:
        allowed-methods: "GET"
  endpoint:
    health:
      show-details: "ALWAYS"

#loggin:
#  level:
#    org:
#      sepringframework:
#        security: DEBUG