spring:
  application:
    name: nosso-cartao-propostas
  output:
    ansi:
      enabled: ALWAYS

  #Conexão com o banco de dados
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      minimum-idle: 10
      maximum-pool-size: 20
    plataform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${DB_DATABASE:keycloak}
    username: ${DB_USER:keycloak}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update

  #Configuração de Segurança
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:18080}/auth/realms/cartao-proposta
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:18080}/auth/realms/cartao-proposta/protocol/openid-connect/certs
auth:
  client_id: cliente-proposta
  client_secret: 7e3fccad-d14b-4742-a2c7-d9213b97e5e4
  uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:18080}/auth/realms/cartao-proposta/protocol/openid-connect/token
  grant_type: password
  scope: proposta

#Variáveis de ambiente para o Feign
uri_analise_financeira: ${URI_ANALISE:http://localhost:9999/}
uri_cartao: ${URI_CARTAO:http://localhost:8888/}

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    io:
      zup:
        orange:
          propostaspring:
            registroCartao:
              bloqueios:
                CartaoGatewy: DEBUG

#Actuators e Prometheus
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

# Jaeger - Habilita ou não
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    service-name: propostas
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}