spring:
  application:
    name: nosso-cartao-propostas
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      minimum-idle: 10
      maximum-pool-size: 20
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

uri_analise_financeira: http://localhost:9999/

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

logging.level.io.zup.orange.propostaspring.registroProposta.analiseFinanceira.AnaliseFinanceiraDeClientes: DEBUG
#spring:
#  datasource:
#    url: jdbc:h2:mem:proposta
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    database-plataform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernates:
#        show_sql: true
#        format_sql: true