spring:
  application:
    name: nosso-cartao-propostas
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      minimum-idle: 10
      maximum-pool-size: 20
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
    password: password
  jpa:
    hibernate:
      ddl-auto: update

uri_analise_financeira: "http://localhost:9999/"
uri_cartao: "http://localhost:8888/"

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

logging.level.io.zup.orange.propostaspring.registroProposta.analiseFinanceira.AnaliseFinanceiraDeClientes: DEBUG

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:9999/"
        allowed-methods: "GET"
  endpoint:
    health:
      show-details: "ALWAYS"
